"""base

Revision ID: 7f1ad0bdf797
Revises: 
Create Date: 2021-05-25 13:21:12.668316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f1ad0bdf797'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot__intent',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('bot__user',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('bot__message',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('intent_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['intent_uuid'], ['bot__intent.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['bot__user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('bot__reply',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('message_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['message_uuid'], ['bot__message.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot__reply')
    op.drop_table('bot__message')
    op.drop_table('bot__user')
    op.drop_table('bot__intent')
    # ### end Alembic commands ###
