"""intent

Revision ID: aacd14d2ea5f
Revises: ae9045472d6e
Create Date: 2021-05-25 13:38:33.303269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacd14d2ea5f'
down_revision = 'ae9045472d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot__intent', sa.Column('response', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot__intent', 'response')
    # ### end Alembic commands ###
